export class Position {
}

export enum PositionEnum {

  //NEW enums, as used by backend
  Quarry=<any>"Quarry",
  Sled=<any>"Sled",
  Pyramid=<any>"Pyramid",
  Temple=<any>"Temple",
  BurialChamber=<any>"BurialChamber",
  Obelisk=<any>"Obelisk",
  Market=<any>"Market",
  DepartingHarbour=<any>"DepartingHarbour",
  PlayerCardStack=<any>"PlayerCardStack",


  //TODO remove old enums
  unknown=<any>"unknown",
  market=<any>"market",
  marketSlot1=<any>"marketSlot1",
  marketSlot2=<any>"marketSlot2",
  marketSlot3=<any>"marketSlot3",
  marketSlot4=<any>"marketSlot4",
  pyramid=<any>"pyramid",
  pyramidSlot1=<any>"pyramidSlot1",
  pyramidSlot2=<any>"pyramidSlot2",
  pyramidSlot3=<any>"pyramidSlot3",
  pyramidSlot4=<any>"pyramidSlot4",
  pyramidSlot5=<any>"pyramidSlot5",
  pyramidSlot6=<any>"pyramidSlot6",
  pyramidSlot7=<any>"pyramidSlot7",
  pyramidSlot8=<any>"pyramidSlot8",
  pyramidSlot9=<any>"pyramidSlot9",
  pyramidSlot10=<any>"pyramidSlot10",
  pyramidSlot11=<any>"pyramidSlot11",
  pyramidSlot12=<any>"pyramidSlot12",
  pyramidSlot13=<any>"pyramidSlot13",
  pyramidSlot14=<any>"pyramidSlot14",
  temple=<any>"temple",
  templeSlot1=<any>"templeSlot1",
  templeSlot2=<any>"templeSlot2",
  templeSlot3=<any>"templeSlot3",
  templeSlot4=<any>"templeSlot4",
  templeSlot5=<any>"templeSlot5",
  burialChamber=<any>"burialChamber",
  burialChamberSlot1=<any>"burialChamberSlot1",
  burialChamberSlot2=<any>"burialChamberSlot2",
  burialChamberSlot3=<any>"burialChamberSlot3",
  burialChamberSlot4=<any>"burialChamberSlot4",
  burialChamberSlot5=<any>"burialChamberSlot5",
  burialChamberSlot6=<any>"burialChamberSlot6",
  burialChamberSlot7=<any>"burialChamberSlot7",
  burialChamberSlot8=<any>"burialChamberSlot8",
  burialChamberSlot9=<any>"burialChamberSlot9",
  burialChamberSlot10=<any>"burialChamberSlot10",
  burialChamberSlot11=<any>"burialChamberSlot11",
  burialChamberSlot12=<any>"burialChamberSlot12",
  burialChamberSlot13=<any>"burialChamberSlot13",
  burialChamberSlot14=<any>"burialChamberSlot14",
  burialChamberSlot15=<any>"burialChamberSlot15",
  burialChamberSlot16=<any>"burialChamberSlot16",
  burialChamberSlot17=<any>"burialChamberSlot17",
  burialChamberSlot18=<any>"burialChamberSlot18",
  burialChamberSlot19=<any>"burialChamberSlot19",
  burialChamberSlot20=<any>"burialChamberSlot20",
  burialChamberSlot21=<any>"burialChamberSlot21",
  burialChamberSlot22=<any>"burialChamberSlot22",
  burialChamberSlot23=<any>"burialChamberSlot23",
  burialChamberSlot24=<any>"burialChamberSlot24",
  burialChamberSlot25=<any>"burialChamberSlot25",
  burialChamberSlot26=<any>"burialChamberSlot26",
  obelisks=<any>"obelisk",
  obeliskSlot1=<any>"obeliskSlot1",
  obeliskSlot2=<any>"obeliskSlot2",
  obeliskSlot3=<any>"obeliskSlot3",
  obeliskSlot4=<any>"obeliskSlot4",
  player1=<any>"player1",
  player2=<any>"player2",
  player3=<any>"player3",
  player4=<any>"player4",
  ship1=<any>"ship1",
  ship1Slot1=<any>"ship1Slot1",
  ship1Slot2=<any>"ship1Slot2",
  ship1Slot3=<any>"ship1Slot3",
  ship1Slot4=<any>"ship1Slot4",
  ship2=<any>"ship2",
  ship2Slot1=<any>"ship2Slot1",
  ship2Slot2=<any>"ship2Slot2",
  ship2Slot3=<any>"ship2Slot3",
  ship2Slot4=<any>"ship2Slot4",
  ship3=<any>"ship3",
  ship3Slot1=<any>"ship3Slot1",
  ship3Slot2=<any>"ship3Slot2",
  ship3Slot3=<any>"ship3Slot3",
  ship3Slot4=<any>"ship3Slot4",
  ship4=<any>"ship4",
  ship4Slot1=<any>"ship4Slot1",
  ship4Slot2=<any>"ship4Slot2",
  ship4Slot3=<any>"ship4Slot3",
  ship4Slot4=<any>"ship4Slot4",
  supplySled=<any>"supplySled",
  stoneQuarry=<any>"stoneQuarry",
  departingHarbour1=<any>"departingHarbour1",
  departingHarbour2=<any>"departingHarbour2",
  departingHarbour3=<any>"departingHarbour3",
  departingHarbour4=<any>"departingHarbour4",
  arrivingHarbour1=<any>"arrivingHarbour1",
  arrivingHarbour2=<any>"arrivingHarbour2",
  arrivingHarbour3=<any>"arrivingHarbour3",
  arrivingHarbour4=<any>"arrivingHarbour4",
  arrivingHarbour5=<any>"arrivingHarbour5",

}

interface IPositionEnum{
  value: string;
  name: PositionEnum;
}
